services:
  postgres:
    image: postgres:17
    container_name: postgres-1
    environment:
      POSTGRES_USER: testcontainer
      POSTGRES_PASSWORD: testcontainer123
      POSTGRES_DB: testcontainersdb
    ports:
      - "5433:5432"
    networks:
      - gotestcon
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testcontainer"]
      interval: 10s
      timeout: 5s
      retries: 5

  goapp:
    build: .
    container_name: goapp-1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TESTPORTADDR: ':9191'
      TESTCONADDR: 'postgres://testcontainer:testcontainer123@postgres-1:5432/testcontainersdb?sslmode=disable'
    ports:
      - "9191:9191"
    networks:
      - gotestcon

  migrate:
    image: migrate/migrate
    volumes:
      - ${PWD}/project/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://testcontainer:testcontainer123@postgres-1/testcontainersdb?sslmode=disable", "up", "3"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gotestcon

networks:
  gotestcon:
