name: TestContainers

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Build the Docker image
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag gotestcon

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker tag gotestcon ${{ secrets.DOCKER_USERNAME }}/gotestcon:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gotestcon:latest

  Test:
    runs-on: ubuntu-latest
    needs: Build
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USER: testcontainer
          POSTGRES_PASSWORD: testcontainer123
          POSTGRES_DB: testcontainersdb

    steps:
      # Checkout the repository (needed for source code access)
      - uses: actions/checkout@v4

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull the Docker image from DockerHub
      - name: Pull Docker image from DockerHub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/gotestcon:latest

      # Run the Container and Execute Tests
      - name: Run Tests in Docker Container
        run: |
          # Start the container
          docker run  -d --name gotestcon-container \
            -e TESTCONADDR='postgres://testcontainer:testcontainer123@postgres:5432/testcontainersdb?sslmode=disable' \
            --network host \
            ${{ secrets.DOCKER_USERNAME }}/gotestcon:latest

          # Wait for the container to be ready
          for i in {1..10}; do
            if [ "$(docker inspect -f '{{.State.Running}}' gotestcon-container)" == "true" ]; then
              break
            fi
            sleep 1
          done

          # Run the tests
          docker exec gotestcon-container go test -v ./...

          # Cleanup
          docker stop gotestcon-container
          docker rm gotestcon-container

  Build-and-Test-Dockercompose:
    runs-on: ubuntu-latest
    needs: Test

    services:
      postgres:
        image: postgres:17
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U testcontainer"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Check out my code
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        run: |
          docker compose up -d

      - name: Wait for services to be healthy
        run: docker compose ps
      
      - name: Run Migrations
        run: |
          docker compose run migrate
      
      - name: Run Tests
        run: |
          docker-compose run goapp go test ./...

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
