name: Golang Testcontainers

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v4
        with: 
           go-version: '1.22'

      - name: Build Golang 
        run: go build -v ./...

      - name: Test Golang
        run: go test -v ./...
