name: Golang Testcontainers

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v4
        with: 
           go-version: '1.22'

      - name: Build Golang 
        run: go build -v ./...

      - name: Test Golang
        run: go test -v ./...

  BuildDocker:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        run: docker build . --file Dockerfile --tag gotest

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Dockerhub
        run: |
          docker tag gotest ${{ secrets.DOCKER_USERNAME }}/gotest:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gotest:latest
