name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testcontainer
          POSTGRES_PASSWORD: testcontainer123
          POSTGRES_DB: testcontainersdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testcontainer -d testcontainersdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/gotest:latest

    - name: Install grpcurl
      run: |
          curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz -o grpcurl.tar.gz
          tar -xvf grpcurl.tar.gz
          sudo mv grpcurl /usr/local/bin

    - name: Set up Docker Compose
      run: docker compose up -d

    - name: Wait for PostgreSQL to be healthy
      run: |
        until docker exec postgres pg_isready -U testcontainer -d testcontainersdb; do
          echo "Waiting for database to be ready..."
          sleep 5
        done

    - name: Run Migrations
      run: docker compose up migrate

    - name: Run Tests
      run: docker compose run goapp go test ./...

